# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

project = "Soapbox.xcodeproj"

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    update_code_signing_settings(use_automatic_signing: false, path: "Soapbox.xcodeproj")

    match(
      app_identifier: "app.social.soapbox",
      type: "appstore"
    )

    update_project_provisioning(
      xcodeproj: "Soapbox.xcodeproj",
      target_filter: "Soapbox",
      profile:ENV["sigh_app.social.soapbox_appstore_profile-path"],
      build_configuration: "Release"
    )

    current = get_version_number(xcodeproj: project)
    increment_version_number(version_number: current)

    UI.message "current version is #{current}"
    type = UI.select("What type of release is this?: ", ["major", "minor", "patch"])

    increment_version_number(bump_type: type, xcodeproj: project)

    changelog = read_changelog(section_identifier: '[Unreleased]')
    set_changelog(changelog: changelog)

    gym(
      workspace: "Soapbox.xcworkspace",
      scheme:"Soapbox",
      configuration: "Release",
      clean: true,
      export_method: "app-store",
      output_directory:"./build/",
      export_options: {
        method: "app-store",
        provisioningProfiles: {
          "app.social.soapbox" => ENV["sigh_app.social.soapbox_appstore_profile-name"]
        }
      },
      codesigning_identity:"Apple Distribution: Dean Eigenmann (Z9LC5GZ33U)",
      output_name: "Soapbox.ipa"
    )

    stamp_changelog(section_identifier: "#{get_version_number(project)}")
    upload_to_app_store
  end

  lane :beta do
    update_code_signing_settings(use_automatic_signing: false, path: "Soapbox.xcodeproj")

    match(
      app_identifier: "app.social.soapbox",
      type: "appstore"
    )

    update_project_provisioning(
      xcodeproj: "Soapbox.xcodeproj",
      target_filter: "Soapbox",
      profile:ENV["sigh_app.social.soapbox_appstore_profile-path"],
      build_configuration: "Release"
    )

    build_number = latest_testflight_build_number + 1

    increment_build_number({
      build_number: build_number
    })

    gym(
      workspace: "Soapbox.xcworkspace",
      scheme:"Soapbox",
      configuration: "Release",
      clean: true,
      export_method: "app-store",
      output_directory:"./build/",
      export_options: {
        method: "app-store",
        provisioningProfiles: {
          "app.social.soapbox" => ENV["sigh_app.social.soapbox_appstore_profile-name"]
        }
      },
      codesigning_identity:"Apple Distribution: Dean Eigenmann (Z9LC5GZ33U)",
      output_name: "Soapbox.ipa"
    )
    
    changelog = read_changelog
    upload_to_testflight(distribute_external: true, changelog: changelog, groups: ["Link", "External", "Airport"])
    stamp_changelog(section_identifier: "Build #{build_number}")
  end
end
