# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "Voicely.xcodeproj")
    build_app(workspace: "Voicely.xcworkspace", scheme: "Voicely")
    upload_to_app_store
  end

  lane :beta do
    disable_automatic_code_signing(path: "Voicely.xcodeproj")

    match(
      app_identifier: "com.voicely.voicely",
      type: "appstore"
    )

    update_project_provisioning(
      xcodeproj: "Voicely.xcodeproj",
      target_filter: "Voicely",
      profile:ENV["sigh_com.voicely.voicely_appstore_profile-path"],
      build_configuration: "Release"
    )

    increment_build_number({
      build_number: latest_testflight_build_number + 1
    })

    gym(
      workspace: "Voicely.xcworkspace",
      scheme:"Voicely",
      configuration: "Release",
      clean: true,
      export_method: "app-store",
      output_directory:"./build/",
      export_options: {
        method: "app-store",
        provisioningProfiles: {
          "com.voicely.voicely" => ENV["sigh_com.voicely.voicely_appstore_profile-name"]
        }
      },
      codesigning_identity:"Apple Distribution: Dean Eigenmann (Z9LC5GZ33U)",
      output_name: "Voicely.ipa"
    )
    upload_to_testflight
  end
end
