name: CI

on:
  pull_request:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/ci.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
      - '!Pods/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: norio-nomura/action-swiftlint@3.1.0
